variable "azclient_id" {}
variable "aztenant_id" {}
variable "azsubscription_id" {}
variable "azclient_secret" {}
variable "environment" {}
variable "gitenv" {}
variable "azadminuser" {}
variable "azadminpw" {}
variable "sharename" {}
variable "region" {}
variable "vnet_ipas" {}
variable "vnet_sec" {}
variable "private_subnets" {}
variable "bastion_subnet" {}
variable "az-rg" {}
variable "sa-name" {}
variable "sa-fsl-name" {}
variable "sa-fsl-ep-name" {}
variable "env" {}
variable "nic-advm-name" {}
variable "ip-nic-advm-name" {}