variable "azclient_id" {}
variable "aztenant_id" {}
variable "azsubscription_id" {}
variable "azclient_secret" {}
variable "environment" {}
variable "gitenv" {}
variable "sharename" {}
variable "region" {}
variable "vnet_ipas" {}
variable "private_subnets" {}
variable "az-rg" {}
variable "sa-name" {}
variable "sa-fsl-name" {}
variable "sa-fsl-ep-name" {}
variable "env" {}